### ISSUE TITLE
Corrupted world/

### ISSUE THREAD

**Issue by FormedXxFreakxX** [OpenMods/OpenPeripheral-Addons#29]
Placing a Peripheral Proxy next to a Hardened Energy Cell from Thermal Expansion corrupts the save making it unusable

OP Core: 0.3.1
OP Addons: 0.1.1
TE: 3.0.0.7

**Comment by nevercast** [comment]
"I was unable to recreate the error using a newest version of OPC and OPA. The map is still unusable however."

Use MCEdit to fix if you still have a world save with this issue, delete any offending tile entities.
This issue is almost a year old now and you've mentioned it's not a problem with up-to-date versions of OPC and OPA. 

Closing as invalid.
